# -*- coding: utf-8 -*-
"""Datos maestros del curso: estudiantes y modulos."""

CURSO = {
    "titulo": "Microsoft Copilot Chat",
    "institucion": "Universidad Piloto de Colombia",
    "empresa": "Falabella",
    "grupo": "Grupo 2",
    "sp_sitio": "https://upcedu-my.sharepoint.com/personal/instructor6-cta_unipiloto_edu_co",
    "sp_ruta_base": "/personal/instructor6-cta_unipiloto_edu_co/Documents/Moodle u piloto Falabella grupo 2",
    "sp_carpeta": ("https://upcedu-my.sharepoint.com/:f:/r/personal/instructor6-cta_unipiloto_edu_co"
                   "/Documents/Moodle%20u%20piloto%20Falabella%20grupo%202"),
    "hoja": "https://docs.google.com/spreadsheets/d/1HLq_iHm77P71BBsEL6vN7PXTYpEgoPBZPcGWmItpfX4/edit",
}

MODULOS = [
    {
        "n": 1,
        "carpeta": "Modulo 1 - Diagnostico",
        "sp": "Modulo 1",
        "actividad": "Actividad 00",
        "titulo": "Diagnóstico del problema",
        "corto": "Diagnostico",
        "resumen": "Analiza un proceso real de tu área con apoyo de IA: causas, actores, evidencias e impactos.",
        "peso": "20%",
        "modalidad": "Individual o en pareja",
        "formato_txt": "PDF de 3 a 5 páginas",
        "pdf": "Actividad_0_Diagnostico.pdf",
        "requisitos": {"formatos": ["pdf"], "paginasMin": 3, "paginasMax": 5},
        "criterios": [
            "Claridad en la delimitación del problema",
            "Pertinencia del proceso seleccionado",
            "Calidad del análisis de causas e impactos",
            "Uso crítico y documentado de herramientas de IA",
        ],
        "entregables": [
            "Documento en PDF de 3 a 5 páginas con estructura clara y conclusiones",
            "Mínimo 3 evidencias: datos, testimonios, tiempos, ejemplos, documentos o capturas",
            "Bitácora con los prompts usados y cómo validaste o ajustaste las respuestas",
        ],
    },
    {
        "n": 2,
        "carpeta": "Modulo 2 - Infografia",
        "sp": "Modulo 2",
        "actividad": "Actividad 01",
        "titulo": "Infografía de la solución propuesta",
        "corto": "Infografia",
        "resumen": "Representa visualmente el proceso, sus cuellos de botella y la solución con IA que propones.",
        "peso": "25%",
        "modalidad": "Individual o en pareja",
        "formato_txt": "PDF o imagen PNG/JPG de alta resolución, mínimo 1920 px de ancho",
        "pdf": "Actividad_1_Infografia.pdf",
        "requisitos": {"formatos": ["pdf", "png", "jpg", "jpeg"], "anchoMin": 1920},
        "criterios": [
            "Claridad en la identificación del problema",
            "Coherencia de la solución propuesta",
            "Calidad del diseño visual",
            "Uso apropiado de elementos gráficos",
        ],
        "entregables": [
            "Infografía en PDF o imagen de mínimo 1920 px de ancho",
            "Mínimo 5 elementos visuales diferenciados",
            "Encabezado, diagnóstico, propuesta IA, beneficios y herramientas",
        ],
    },
    {
        "n": 3,
        "carpeta": "Modulo 3 - Documento de solucion",
        "sp": "Modulo 3",
        "actividad": "Actividad 02",
        "titulo": "Documento de la solución",
        "corto": "Documento-Solucion",
        "resumen": "Describe qué vas a implementar, cómo funcionará, con qué herramientas y qué beneficios esperas.",
        "peso": "25%",
        "modalidad": "En grupo, máximo 3 personas",
        "formato_txt": "Word (.docx) o PDF, de 4 a 6 páginas",
        "pdf": "Actividad_2_Documento_Solucion.pdf",
        "requisitos": {"formatos": ["pdf", "docx"], "paginasMin": 4, "paginasMax": 6},
        "criterios": [
            "Coherencia entre problema y solución",
            "Claridad en la descripción funcional",
            "Viabilidad de las herramientas propuestas",
            "Calidad del documento generado con IA",
        ],
        "entregables": [
            "Documento de 4 a 6 páginas en Word o PDF",
            "Un esquema, diagrama o tabla del flujo de la solución",
            "Al menos 2 casos de uso demostrables en el prototipo",
            "Los prompts usados y los ajustes realizados",
        ],
    },
    {
        "n": 4,
        "carpeta": "Modulo 4 - Manual del sistema",
        "sp": "Modulo 4",
        "actividad": "Actividad 03",
        "titulo": "Manual del sistema o asistente de IA",
        "corto": "Manual",
        "resumen": "Documenta tu asistente: objetivo, arquitectura, guía de uso paso a paso y limitaciones.",
        "peso": "35%",
        "modalidad": "Individual",
        "formato_txt": "Word (.docx) o PDF, mínimo 8 páginas de contenido",
        "pdf": "Actividad_3_Manual.pdf",
        "requisitos": {"formatos": ["pdf", "docx"], "paginasMin": 8, "imagenesMin": 3},
        "criterios": [
            "Estructura y organización del documento",
            "Claridad en las instrucciones",
            "Completitud de la información",
            "Ejemplos prácticos de uso incluidos",
        ],
        "entregables": [
            "Manual en Word o PDF (el enunciado pide mínimo 8 páginas de contenido)",
            "Al menos 3 capturas de pantalla o diagramas del asistente",
            "Portada, objetivo, arquitectura, guía de uso y limitaciones",
            "Los prompts usados y los ajustes realizados",
        ],
    },
    {
        "n": 5,
        "carpeta": "Modulo 5 - Presentacion final",
        "sp": "Modulo 5",
        "actividad": "Actividad 04",
        "titulo": "Presentación final y prototipo en vivo",
        "corto": "Presentacion",
        "resumen": "Expón diagnóstico, solución y demuestra el prototipo funcionando en vivo ante el jurado.",
        "peso": "40%",
        "modalidad": "En grupo, máximo 3 personas",
        "formato_txt": "PPT o PDF, mínimo 10 diapositivas, más demostración en vivo",
        "pdf": "Actividad_4_Presentacion.pdf",
        "requisitos": {"formatos": ["pptx", "pdf", "ppt"], "paginasMin": 10},
        "criterios": [
            "Identificación clara del problema",
            "Viabilidad técnica de la solución",
            "Funcionamiento del prototipo en vivo",
            "Calidad de la presentación oral",
        ],
        "entregables": [
            "Presentación de mínimo 10 diapositivas en PPT o PDF",
            "Prototipo operando en vivo, no grabaciones",
            "Al menos 2 casos de uso demostrados",
            "Duración 12 a 15 minutos más 5 de preguntas",
        ],
    },
]
